Hoff 617
UKHomeOffice/lmr pull request #17
Opened 2024-02-29 16:18 UTC by adityababumallisettiHO

2024-03-04 16:43 UTC, sulthan-ahmed commented on .drone.yml
> +  # NOTIFY_STUB: stub
suggest deleting this

2024-03-04 16:44 UTC, sulthan-ahmed commented on .drone.yml
> +  #     event: promote
probably best to delete it tbh

2024-03-04 16:51 UTC, sulthan-ahmed commented on .drone.yml
> +  #     event: cron
prob delete tbh

2024-03-04 16:52 UTC, sulthan-ahmed commented on .snyk
> +patch: {}
new line?

2024-03-04 16:58 UTC, sulthan-ahmed commented on .drone.yml
> +
do you think we can simplify all of this for all the different environments, because it's just running the same steps

2024-03-11 15:23 UTC, adityababumallisettiHO commented
Waiting for @mislam987 to get back on the commented Drone CI steps. I have requested @mislam987 to check with the team if we require these steps or remove them for now?

2024-03-13 14:34 UTC, sulthan-ahmed commented
ok @adityababumallisettiHO

2024-03-20 22:00 UTC, adityababumallisettiHO commented on .drone.yml
> +  # NOTIFY_STUB: stub
This has been deleted. I have also checked with Muhammed Islam and Rhodine

2024-03-20 22:07 UTC, adityababumallisettiHO commented on .drone.yml
> +  #     event: cron
We have been using this step for rest of services. We need to run this cron step of cloning the repos to scan vulnerabilities with Snyk. I have uncommented this step.

2024-03-26 20:59 UTC, adityababumallisettiHO commented on .drone.yml
> +
I have looked into it. I believe it is better to leave it as it is. It is difficult to use this step for all the envs as the conditions are different for not-prod and prod.

2024-04-09 08:52 UTC, jamiecarterHO requested changes
Just one thing I found to update.

Other is that there is a new vuln in the pipeline for notifications-node-client. As its a new service perhaps notifications-node-client v8.0.0 could be used? I believe this vuln is fixed there.

2024-04-09 10:44 UTC, adityababumallisettiHO commented on sonar-project.properties
> +sonar.projectName=Illegal-Migration-Act
I have replaced them with Landlords-Make-A-Report

2024-04-09 10:45 UTC, adityababumallisettiHO commented
Added notifications-node-client v8.0.0 resolves vulnerability in package.json

2024-04-09 15:32 UTC, adityababumallisettiHO commented
There is a ticket temi is working on fixing these vulnerabilties
https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-694

I have added a ticket for LMR service 
https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-696
and for LCS which is cloned version of LMR service 
https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-697

2024-04-11 08:55 UTC, jamiecarterHO commented
@adityababumallisettiHO I suppose you could add the new vulnerabilities that can't be updated in the project to the snyk whitelist

2024-04-22 11:26 UTC, adityababumallisettiHO commented
Hi @jamiecarterHO ,
Vulnerabilities have been added to snyk ignore file.
We have all checks passed.
Drone CI: https://drone-gh.acp.homeoffice.gov.uk/UKHomeOffice/lmr/270

<img width="1439" alt="image" src="https://github.com/UKHomeOffice/lmr/assets/146218064/a0199d04-ce0a-4737-8a59-37217e682748">

2024-04-22 13:33 UTC, jamiecarterHO approved these changes
Looks good, I can see build is all green for branch pipeline and scanners running.
Make sure to squash those commits and check the commit notes :)

2024-04-22 14:55 UTC, merged